### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by jgw2001** [jcchikikomori/GmsCoreHuawei#12]
Just thank you for making updates to the GmsCore for the Huawei. 

Just a few suggestions going forward, for GMS services that are not supported by MicroG, how easy do you think from your experience to dynamically link to the HMS services instead. 

For example, the GMS services (if it exists) calls on the google photo/map or notifications, they are redirected to the HMS services instead. 

Looks as if Huawei has virtually copied most of the GMS services allowing applications to easily be transferred over with little effort, surly making dynamic links could be an answer. 

There are other advantages:

-GMSCore will not use up as many resources
-Give the user a more universal HMS experience
-Increase the number of applications supported. 

Another option, for services not supported by HMS, function to download the google services, run in a sandbox and dynamically linking to those services/libs when services are not supported by HMS or MicroG.

Your thoughts?

**Comment by jcchikikomori** [comment]
> Just a few suggestions going forward, for GMS services that are not supported by MicroG, how easy do you think from your experience to dynamically link to the HMS services instead.
>
> For example, the GMS services (if it exists) calls on the google photo/map or notifications, they are redirected to the HMS services instead.
> 
> Looks as if Huawei has virtually copied most of the GMS services allowing applications to easily be transferred over with little effort, surly making dynamic links could be an answer.
> 
> There are other advantages:
> 
> -GMSCore will not use up as many resources
> -Give the user a more universal HMS experience
> -Increase the number of applications supported.
>

**IMO**

Unfortunately, due to the US sanctions to Huawei, they are not allowed to simply replicate the structure of Google Services just for notifications, etc.

That is why YouTube Vanced choose to fork the microG then change the Application ID, then faked the signatures, added optimizations, and voila, a working YouTube for Google-less device

> Another option, for services not supported by HMS, function to download the google services, run in a sandbox and dynamically linking to those services/libs when services are not supported by HMS or MicroG.
> 

You can do that on non-Huawei devices. I was just sad for the @EloYGomeZ's fork because of their messy code being made and being published the build online, so i wanted a cleaner & more stable code of microG with patches provided by @YTVanced

**What else to do next?**

I don't know what to do next.
I don't have enough resources and time to modify a Google-dependent application, and patch with our own microG

So all i have to do by now is to update the microG. Who knows?
